### ISSUE TITLE
Remove or loosen "engines" constraint in package.json

### ISSUE THREAD

**Issue by Wedvich** [webalys-hq/streamlinehq-npm#1]
We're trying to use the package in our project, and currently it requires an exact match for the Node/NPM versions:

```json
"engines": {
    "node": "14.15.0",
    "npm": "6.14.8"
}
```

Are these constraints necessary? Or if they are, would it be possible to loosen the constraints to a reasonable minimum like below?

```json
"engines": {
    "node": "^14",
    "node": "^6",
}
```

Right now the package won't even install - using `--ignore-engines` makes the installation proceed to the postinstall step, but then it fails there instead.

**Comment by cbrwizard** [comment]
You're right, they weren't needed. I've removed them in release 1.0.4, please update
