### ISSUE TITLE
Installing Streamline assets failed - Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by atbostudio** [webalys-hq/streamlinehq-npm#10]
Hello,

for security reasons we are working behind a corporate proxy.

While installing @streamlinehq/streamlinehq we retrieve following error.

Installing Streamline assets for ...
**API error: self signed certificate in certificate chain**
Error: **self signed certificate in certificate chain**
    at TLSSocket.onConnectSecure (_tls_wrap.js:1321:34)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket._finishInit (_tls_wrap.js:794:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:608:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'
}

we already tried to add our ca file using `npm config set cafile` but it is still not working.
any suggestions?

the previous npm packages worked well

kind regards

**Comment by atbostudio** [comment]
as your method to gather the icons from an external api endpoint using a embeded node application we needed to add our corporate cacerts to our specific node version.

on windows:
`set NODE_EXTRA_CA_CERTS=C:\\path\\to\\cacerts.pem`

**Comment by cbrwizard** [comment]
I'm glad you were able to resolve this issue. Thank you for sharing the solution as well!
