### ISSUE TITLE
Missing svg files in node_module folder

### ISSUE THREAD

**Issue by behz** [webalys-hq/streamlinehq-npm#11]
Hello,  I just started implementing npm in our project. npm module seems installed correctly and I can see some icons on my app, although. seems there are missing icons like this "Travel Hotel 5 Star" that I need to use 

I find the icon on https://app.streamlinehq.com/icons/streamline-bold  search  but the svg file is not in my node_module folder

missing:
node_modules/@streamlinehq/streamlinehq/img/streamline-bold/travel-hotel-5-star-sjs9Ht.svg

I tried to re install the module 3 times, still same:
<img width="620" alt="Screen Shot 2021-04-01 at 19 19 43" src="https://user-images.githubusercontent.com/3495334/113312203-b75dbc00-9312-11eb-8658-0c3b283c1fbf.png">

btw I use Yarn, and has this line in package.json file `"@streamlinehq/streamlinehq": "^2.1.0",`

**Comment by kwesterfeld2** [comment]
A variant of this problem is that we have about 80 imported icons with old path names and I'm struggling to find the paths for each of these to the new flattened SVG hierarchy.

What I need: a way to take the prior mapping and give me the new one.  Finding the original icons in the streamline app is hugely time consuming.  It will probably take me 6-7 hours at the rate I am going.

**Comment by behz** [comment]
Thanks for the quick reply
I'll use a simple Star for now.  no rush, I'll replace them with Travel Hotel Star when this is fixed. thanks

**Comment by Thomascogez** [comment]
@kwesterfeld2 I'll ask for a CSV that expose old icons name with the new one, i'm waiting for it you can follow the status of my issue here https://github.com/webalys-hq/streamlinehq-npm/issues/9

**Comment by onhate** [comment]
I have like 90 icons in my app and really don't wanna do manual replace for each one of them, why this hash by the way?

**Comment by cbrwizard** [comment]
Please see my comment on this issue here https://github.com/webalys-hq/streamlinehq-npm/issues/9#issuecomment-815575963

**Comment by LucasKristandt** [comment]
fresh streamline installs icons without hash and uses "images" instead of "img" subfolder.

**Comment by cbrwizard** [comment]
We have recently recreated all assets and released a new NPM 3.0.1 version https://github.com/webalys-hq/streamlinehq-npm/releases/tag/3.0.1, please install it, fetch newest images and check if it helps you. Now images are imported differently and should always be found.

**Comment by cbrwizard** [comment]
Closing this issue since I believe it's fixed. Feel free to respond if you think otherwise
