### ISSUE TITLE
Mini Bold icons missing stroke-width="0"

### ISSUE THREAD

**Issue by kwesterfeld2** [webalys-hq/streamlinehq-npm#12]
The use of the bold icons here (and perhaps others) are missing stroke-width="0", which dramatically alters their appearance and seems incorrect.

@streamlinehq/streamlinehq/img/streamline-mini-bold/interface-signal-graph-circle-fSZsW6.svg
@streamlinehq/streamlinehq/img/streamline-mini-bold/interface-arrows-button-down-wvSWQD.svg
@streamlinehq/streamlinehq/img/streamline-mini-bold/interface-help-question-circle-9ULQpG.svg
@streamlinehq/streamlinehq/img/streamline-mini-bold/interface-user-circle-Q3ywqY.svg

For these SVG using fill, the reliance on stroke-width 0 creates their "bold" effect, which when missing defeats the purpose (they appear hairline).

Example of our topnav with prior edition of streamline components:
![image](https://user-images.githubusercontent.com/38136866/113506115-d9249200-9510-11eb-9e97-ab0451ccc7c4.png)

And now without stroke-width="0":
![image](https://user-images.githubusercontent.com/38136866/113506118-e6da1780-9510-11eb-9c9e-0b2e17df22fa.png)

**Comment by cbrwizard** [comment]
Thank you for reporting this. It's indeed an issue and we will fix all SVGs with this missing attribute.

**Comment by cbrwizard** [comment]
This should be fixed now, please validate

**Comment by cbrwizard** [comment]
I assume this is done. Please leave the comment if it's not
