### ISSUE TITLE
Unable to resolve some icons

### ISSUE THREAD

**Issue by stigvanbrabant** [webalys-hq/streamlinehq-npm#16]
`
import InterfaceSettingMenuVertical from '@streamlinehq/streamlinehq/img/streamline-bold/interface-setting-menu-vertical-Nc3niS.svg';
`

this icon import fails to resolve, other icons work fine.

version of `@streamlinehq/streamlinehq` is `2.1.0`.

**Comment by sklink** [comment]
Quite a few from the `streamline-bold` package are failing to resolve. If you need me to list them out let me know.

**Comment by tomexx** [comment]
Yes, a lot of icons, cannot be loaded, e.g.:

```
Module not found: Can't resolve '@streamlinehq/streamlinehq/img/streamline-bold/interface-alert-alarm-bell-2-fSZlC1.svg' ...
```

**Comment by cbrwizard** [comment]
Duplicate of https://github.com/webalys-hq/streamlinehq-npm/issues/11
We're working on fixing this
