### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by stigvanbrabant** [webalys-hq/streamlinehq-npm#17]
![image](https://user-images.githubusercontent.com/14889538/115719119-15167e80-a37c-11eb-8162-2d459c086d76.png)
when removing all previous streamline configurations from the npm configurations (as advised inside the readme) i get the above error

**Comment by stigvanbrabant** [comment]
when leaving the configuration inside .npmrc it does work

**Comment by cbrwizard** [comment]
What's the package you're trying to install? Apparently you have @stremlinehq/stremline-bold in your package.json, which should not be there as it's a deprecated package

**Comment by stigvanbrabant** [comment]
@cbrwizard Yeah it wasn't inside the package.json, but it was still used inside a dependency of the project, my bad. Thanks for the response anyway :)
