### ISSUE TITLE
Icons in streamline-bold have extraneous commas between paths

### ISSUE THREAD

**Issue by GWShark0** [webalys-hq/streamlinehq-npm#18]
**Some context:** we're pulling in icons from `streamline-bold` and running them through [SVGO](https://github.com/svg/svgo) before including them in our React components. We noticed a bit of an oddity when we optimized some of the SVGs coming in from Streamline. Any icon that includes multiple paths (which is most of them) have unnecessary commas present in between the `path` elements. 

For example, a snippet from `layers-back-wvSgsU.svg`
```
stroke-linejoin="round"    />,<path d="M21.5,7h-2a1,1,0,
```

This doesn't seem to have any effect on the SVG itself being rendered (it's valid XML I think?). It is, however, a bit awkward for our particular use case. Tools like [SVGOMG](https://jakearchibald.github.io/svgomg) handle the comma just fine, but it stands out a bit in resulting optimized SVG. I've never seen commas placed in between paths like this in an SVGs before. Sort of wondering if these commas have any purpose or are just an extra artifact of some build process.

<img width="904" alt="Screen Shot 2021-04-26 at 11 49 40 PM" src="https://user-images.githubusercontent.com/2968519/116184394-aaec3980-a6ed-11eb-8df6-7fed7a0919f5.png">

**Comment by cbrwizard** [comment]
Hey, thank you for this report, I've noticed this as well. I'll find a way to automatically remove them.

**Comment by cbrwizard** [comment]
I have removed all extra commas in all images. Reinstall the package to get them fresh.

I'll close the issue since I consider it done but feel free to respond if you still have it.
