### ISSUE TITLE
Icons not loading in NextJS

### ISSUE THREAD

**Issue by Paxatax** [webalys-hq/streamlinehq-npm#25]
I have tried using this package in a NextJS app (version ^10.2.0), and the icons were not showing. I did the same steps in a create-react-app, and it worked.

Steps:
1). Add STREAMLINE_SECRET=... and STREAMLINE_FAMILIES=["streamline-bold"] in .env
2). npm i (and confirm that all icons are listed in node_modules, in @streamlinehq/img)
3). Use it.
```javascript
import GaugeDashboard from '@streamlinehq/streamlinehq/img/streamline-bold/gauge-dashboard-08UEkd.svg';

function index() {
	return (
			<img
				src={GaugeDashboard}
				alt="GaugeDashboard"
				height="30"
				width="30"
			/>
	);
}

export default index;
```

Nothing shows up in the NextJS app. In a useEffect (on init), I console log GaugeDashboard and can see it's an SVG.

In the console it says "**Warning: Invalid value for prop `src` on <img> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM.**" 

Any help would be greatly appreciated.

**Comment by cbrwizard** [comment]
Hey, can you please validate that you have setup your build system to render other, non-Streamline svg files? Because Streamline SVGs should act exactly the same.

Also please log in console the svg contents to validate that it has been imported correctly.

**Comment by Paxatax** [comment]
I resolved my issue.

Rather than using the icons in an img with `src={IconName}`, just import like above, and then use as <IconName /> directly in the template.

Also make sure you have SVGR configured. [Article available here.](https://frontend-digest.com/how-to-import-svgs-into-nextjs-8ec6100e613f)

**Comment by cbrwizard** [comment]
I'm glad that you have resolved your issue and I appreciate that you have shared the solution here as well ❤️
