### ISSUE TITLE
Building1 icon does not allow a fill color

### ISSUE THREAD

**Issue by pixel-glyph** [webalys-hq/streamlinehq-npm#26]
When importing the Building1 icon and setting a fill color, it does not get applied due to the structure of the icon, i.e. the shape that forms the front of the building is not a single entity, and so a fill cannot be applied. It would be great if the SVG could be rebuilt to allow a defined fill and prevent any background color from coming through.

Example of what is desired (with a white fill):
![image](https://user-images.githubusercontent.com/10341564/119411562-9d0fe100-bcb8-11eb-9397-273a6716895f.png)

Example of current state (without a fill):
![image](https://user-images.githubusercontent.com/10341564/119411745-e2cca980-bcb8-11eb-9592-25be938ef739.png)

Specific icon import:
```import Building1 from '@streamlinehq/streamlinehq/img/streamline-regular/building-1-6nlwop.svg'```

Apologies if this is not the right place to raise this issue.

**Comment by cbrwizard** [comment]
Thank you for reporting this. This issue has been sent to our SVG team

**Comment by cbrwizard** [comment]
We have replaces the SVG for this image. Please validate it by reinstalling the npm package and checking it out again

**Comment by pixel-glyph** [comment]
@cbrwizard Awesome, thanks for the quick response!

Unfortunately, after reinstalling the package, the icon appears to be the same.

**Comment by cbrwizard** [comment]
Looks like you're right, we're having a bug with cache. Could you try downloading an SVG directly from this page meanwhile? https://app.streamlinehq.com/icons/streamline-regular/building-construction/buildings/building-1

**Comment by pixel-glyph** [comment]
Thanks @cbrwizard. For now I'll use the SVG directly and update once the caching issue has been resolved 👍

**Comment by cbrwizard** [comment]
We have recently recreated all assets and released a new NPM 3.0.1 version, please install it, fetch newest images and check if it solves your issue.

**Comment by cbrwizard** [comment]
Closing this issue since I believe it's fixed. Feel free to respond if you think otherwise
