### ISSUE TITLE
404 streamline bold package

### ISSUE THREAD

**Issue by stigvanbrabant** [webalys-hq/streamlinehq-npm#29]
I pulled a project (which works on my other device using ubuntu and on a netlify build) onto my macbook. Now when trying to run npm install it throws a 404 for the streamline-bold package.

![image](https://user-images.githubusercontent.com/14889538/121874734-ef687e80-cd07-11eb-8065-6e0fe47e9c02.png)

I configured my streamline throught the streamlinehq.json file:

`{
  "families": ["streamline-regular", "streamline-bold"],
  "secret": "<-- secret token -->"
}`

**Comment by cbrwizard** [comment]
Hey, looks like you're trying to install a deprecated @streamlinehq/streamline-bold package, which you shouldn't, as stated here https://github.com/webalys-hq/streamlinehq-npm#troubleshooting. You just need to install 1 Streamline package: the current one: `@streamlinehq/streamlinehq`.

Also I'd recomment to remove the streamlinehq.json config and use standard .env instead, like described here https://github.com/webalys-hq/streamlinehq-npm#how-to-use

**Comment by stigvanbrabant** [comment]
![image](https://user-images.githubusercontent.com/14889538/121897673-e8029e80-cd22-11eb-84c3-f15fb0d1069d.png)
well @streamlinehq/streamline-bold is not in my package.json, i'm guessing @streamlinehq/streamlinehq still uses the old package to fetch the assets?

**Comment by stigvanbrabant** [comment]
i've also migrated to use the .env file but still nu success

**Comment by cbrwizard** [comment]
Okay, why does your project still try to fetch a deprecated @streamlinehq/streamline-bold package? Maybe something is left inside the *lock file? Try looking for this `streamline-bold` in your project. Also try reinstalling all node_modules.
Also try the solution I've described here https://github.com/webalys-hq/streamlinehq-npm/issues/5#issuecomment-809350883

**Comment by stigvanbrabant** [comment]
Yeah my bad, it's indeed still in the package-lock because of a dependency. Thanks for the quick responses, yeah i updated it but then downgraded it again because i thought it was causing the issue, i will update it to the latest version again.
