### ISSUE TITLE
Got error "You can not download streamline-micro-bold family in SVG"

### ISSUE THREAD

**Issue by theramirobeltran** [webalys-hq/streamlinehq-npm#50]
Error installing Streamline-mini-bold and streamline-micro-bold via npm started about 2 hours ago. Any changes? 

```Reading streamlinehq.json config file
Installing Streamline assets for streamline-bold, streamline-micro-bold, streamline-mini-bold families
Error
Error: Got error "You can not download streamline-micro-bold family in SVG"
    at /opt/app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:4661
    at /opt/app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:1702
    at Object.next (/opt/app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:1807)
    at i (/opt/app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:546)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @streamlinehq/streamlinehq@3.0.3 postinstall: `node build/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @streamlinehq/streamlinehq@3.0.3 postinstall script.```

**Comment by cbrwizard** [comment]
Hey, I believe this has been resolved now. This was a temporary issue on our admin system. Can you please confirm?

**Comment by theramirobeltran** [comment]
Yea thank you. It is working now.

**Comment by benramsay** [comment]
I have the same error with version "@streamlinehq/streamlinehq": "^3.0.4",
Could be a regression ?  
-
npm ERR![0m[91m Installing Streamline assets for streamline-regular, streamline-light, streamline-bold, streamline-micro-bold, streamline-mini-bold families
npm ERR! Error
npm ERR! [0m [91m Error: Got error "You can not download streamline-micro-bold family in SVG"
npm ERR!     at /app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:5775
npm ERR! [0m [91m     at /app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:1702
npm ERR! [0m [91m     at Object.next (/app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:1807)
npm ERR! [0m [91m     at i (/app/node_modules/@streamlinehq/streamlinehq/build/install.js:1:546)

**Comment by fyodoriv** [comment]
@benramsay this might be related to your license. Could you please share your Streamline user's email with support@webalys.com?
