### ISSUE TITLE
Unable to download the icons

### ISSUE THREAD

**Issue by fred-boink** [webalys-hq/streamlinehq-npm#51]
During the post install we are getting the following error:

08:52:19.703 | > node ./postinstall.js
-- | --
08:52:19.993 | > @streamlinehq/streamlinehq@3.0.3 postinstall /vercel/path0/node_modules/@streamlinehq/streamlinehq
08:52:19.993 | > node build/install.js
08:52:20.090 | Installing Streamline assets for streamline-bold, streamline-mini-bold, streamline-micro-bold families
08:52:30.797 | Error parsing JSON from request

 
This happens locally and when we build via Vercel.

**Comment by willrbc** [comment]
```
error An unexpected error occurred: "https://npm.cloudsmith.io/streamlinehq/streamline-icons/@streamlinehq%2fstrealine-icons-react: Not found".
```

Same here

Get this when trying to download, this means I can no longer compile the project

**Comment by thnee** [comment]
Previously there was a `node_modules/@streamlinehq/streamlinehq/img` directory when installing this package, this directory no longer exists when installing the package. This is breaking our build pipeline and blocking work.

**Comment by cbrwizard** [comment]
Hello, we're very sorry about the issues you're having. Unfortunately the streamline npm package architecture is brittle and over-engineered. Please download the images directly from our website and insert them into your project as files which will always be reliable.
