### ISSUE TITLE
Icon naming conflict

### ISSUE THREAD

**Issue by pareeohnos** [webalys-hq/streamlinehq-npm#6]
It seems that there are multiple icons that have the same name based on the main website, and as a result I'm unable to import the correct one. For example, the following two icons are both called `Bin 1` on the website

![streamline-icon-bin-1@140x140-2](https://user-images.githubusercontent.com/1657075/112846943-7c535280-909e-11eb-884c-f1515456e093.png)
![streamline-icon-bin-1@140x140](https://user-images.githubusercontent.com/1657075/112846962-7fe6d980-909e-11eb-81be-ac5dc438588c.png)

And when viewing the relevant `import` statement, they both show

```
import Bin1 from '@streamlinehq/streamlinehq/images/streamline-light/bin-1.svg'
```

When the package downloads all of the icons, the folder only contains a single `bin-1.svg` icon (no copies, or `1.1` or anything) and as such, importing the bin icon that I actually want gives me the wrong icon.

I'm not sure how many icons this is happening to, this is jus the one I've found but I'm sure there are probably more

**Comment by cbrwizard** [comment]
You're right, it's an issue in this package design and it must be fixed.
We will be releasing a 1.1.X version of a package soon which uses an image's name + a shortened part of its id. Eg this `Bin1` image will be available to import as `@streamlinehq/streamlinehq/images/streamline-light/bin-1-n8OgWa.svg`. This means it will be a breaking change unfortunately :\

**Comment by pareeohnos** [comment]
ok great thanks, I can live with that 🙂

**Comment by cbrwizard** [comment]
Done: this change is implemented in version 1.1.1 https://github.com/webalys-hq/streamlinehq-npm/releases/tag/1.1.1. Please note that it introduces a couple of other breaking changes as well.

Please check it out and tell if it solves your issue.

**Comment by timc13** [comment]
This doesn't seem very ergonomic.  Is there somewhere that lists these ids so that we can easily import icons as needed ?

**Comment by cbrwizard** [comment]
It's in the app itself: go to https://app.streamlinehq.com, select a family you're interested in, then select an icon you're interested in and see the import path in the sidebar 
<img width="1621" alt="Screenshot 2021-03-31 at 10 38 30" src="https://user-images.githubusercontent.com/1615659/113108047-41236180-920d-11eb-9aee-aee655141223.png">
Another option is to use an IDE which suggests you to autocomplete a path to an image:
<img width="1171" alt="Screenshot 2021-03-31 at 10 39 32" src="https://user-images.githubusercontent.com/1615659/113108269-7af46800-920d-11eb-8c57-16bb30edc34f.png">

On a side note, we're considering adding plugins to popular IDEs: Visual Studio Code and Webstorm, where you would be able to select an image and paste it in code visually. Another thing we're adding soon is a desktop app with drag&drop support.
